### ISSUE TITLE
Database is empty after creating project

### ISSUE THREAD

**Issue by CedricSchmeits** [0Kit/aiogram_template#2]
After creating a new project with the command:
```
cookiecutter https://github.com/0Kit/aiogram_template.git
```

Setting up the /.env with:
```
BOT_TOKEN=<BOT_TOKEN>
SUPERUSER_ID=<MY_TELEGRAM_ID>

POSTGRES_DB=<DATABASE_NAME>
POSTGRES_USER=<DATABASE_USER>
POSTGRES_PASSWORD=<DATABASE_PASSWORD>
```

Building ans starting the application with:
```
make app-create
```

The application is started within docker.

When I now issue a `/start` command in Telegram to the bot, I'm getting the following error:
```
asyncpg.exceptions.UndefinedTableError: relation "users" does not exist
```

Obviously there are no tables yet creates within the database.

**Comment by CedricSchmeits** [comment]
I had to create the folder: `/migrations/versions`

Else the command: `make makemigrations` would not work

**Comment by 0Kit** [comment]
Read README.md, please
