### ISSUE TITLE
As admin I did not receive "The bot is running!" messages

### ISSUE THREAD

**Issue by CedricSchmeits** [0Kit/aiogram_template#3]
.env file contents
```
...
SUPERUSER_ID=<MY_TELEGRAM_ID>
...
```
I did not know how to fix the issue here so I fixed within the __main__.py line 17:
```
    await utils.notify_admins([int(config.SUPERUSER_ID)])
```
 
This fix is probably not what you had in mind, I would like the suggestion.

**Comment by CedricSchmeits** [comment]
This morning I tought that it would be beter to solve it inside config.py line 14:
```
SUPERUSER_ID = [int(superId) for superId in env.str("SUPERUSER_ID").split(",")]
```

**Comment by 0Kit** [comment]
> This morning I tought that it would be beter to solve it inside config.py line 14:
> ```
> SUPERUSER_ID = [int(superId) for superId in env.str("SUPERUSER_ID").split(",")]
> ```

Will be better, if you do something like this in you main file:
```
await notify_admins([int(config.SUPERUSER_ID)])
```
I will fix it today

**Comment by CedricSchmeits** [comment]
It depends whether you want the posibility for one or more superusers.
